server:
  port: 7770

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiangGuangxing/config-repo
          searchPaths: config
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    port: 15672


