server:
  port: 7770

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiangGuangxing/config-repo.git
#          basedir: target/config
  rabbitmq:
    host: 118.89.245.226
    username: admin
    password: 123456
    port: 15672


